# Generated by Django 3.2.6 on 2021-08-12 18:53

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='글제목')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='글작성일')),
                ('body', models.TextField(null=True, verbose_name='글내용')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/')),
                ('category', models.CharField(choices=[('레시피', '레시피'), ('밀키트', '밀키트')], max_length=1000, verbose_name='글머리')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='users',
            field=models.ManyToManyField(through='expert.Scrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expert',
            name='writer',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_user', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
