# Generated by Django 3.2.3 on 2021-07-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expert', models.ForeignKey(db_column='expert_photo', on_delete=django.db.models.deletion.CASCADE, related_name='expert_photo', to='expert.expert')),
            ],
        ),
    ]
