# Generated by Django 3.2.3 on 2021-07-28 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0004_auto_20210728_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='글작성일'),
        ),
        migrations.AddField(
            model_name='expert',
            name='writer',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_user', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='body',
            field=models.TextField(null=True, verbose_name='글내용'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='글제목'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
