# Generated by Django 3.2.3 on 2021-07-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20210728_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
