# Generated by Django 3.2.3 on 2021-07-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_alter_expert_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='photo',
            new_name='image',
        ),
    ]
