# Generated by Django 3.2.3 on 2021-07-28 05:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_rename_photo_expert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
