# Generated by Django 3.2.3 on 2021-07-29 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0009_alter_expert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='writer',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expert_user', to='accounts.customeruser', verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
