# Generated by Django 3.2.3 on 2021-07-29 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expert', '0010_alter_expert_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='writer',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_user', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
