# Generated by Django 3.2.3 on 2021-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0015_alter_scrap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='category',
            field=models.CharField(choices=[('레시피', '레시피'), ('밀키트', '밀키트')], default=1, max_length=1000, verbose_name='글머리'),
            preserve_default=False,
        ),
    ]
