# Generated by Django 3.2.3 on 2021-08-12 00:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0016_expert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/'),
        ),
    ]
