# Generated by Django 3.2.6 on 2021-08-12 18:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('intro', models.TextField(default='', max_length=30)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='ttgaogawdwdfmexebiwz.jpg', max_length=255, verbose_name='images/')),
                ('basic', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('ingredients', models.TextField(default='', max_length=300)),
                ('option', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('recipy', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
