# Generated by Django 3.2 on 2021-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='text',
        ),
        migrations.AlterField(
            model_name='dish',
            name='intro',
            field=models.CharField(max_length=30),
        ),
    ]
