# Generated by Django 3.2.3 on 2021-08-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_auto_20210804_1934'),
        ('fridge', '0002_auto_20210805_1151'),
    ]

    operations = [
    ]
