# Generated by Django 3.2 on 2021-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_merge_0002_auto_20210804_1934_0002_auto_20210805_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='add',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='main',
        ),
        migrations.AddField(
            model_name='dish',
            name='basic',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(default='', max_length=300),
        ),
    ]
