# Generated by Django 3.2.5 on 2021-08-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_auto_20210802_1504'),
        ('fridge', '0003_auto_20210802_1819'),
    ]

    operations = [
    ]
