# Generated by Django 3.2.6 on 2021-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipy',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
