# Generated by Django 3.2.6 on 2021-08-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='loaddish.jpg', upload_to='images/'),
        ),
    ]
