# Generated by Django 3.2.6 on 2021-08-12 18:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='ttgaogawdwdfmexebiwz.jpg', max_length=255, verbose_name='images/'),
        ),
    ]
