# Generated by Django 3.2.6 on 2021-08-07 21:29

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20210807_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
