# Generated by Django 3.2 on 2021-08-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20210807_2112'),
        ('community', '0011_post_tag'),
    ]

    operations = [
    ]
