# Generated by Django 3.2.3 on 2021-08-05 11:51

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeruser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
