# Generated by Django 3.2.6 on 2021-08-05 18:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210805_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/face.png', upload_to='images/'),
        ),
    ]
