# Generated by Django 3.2.6 on 2021-08-05 18:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customeruser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/face.jpg', upload_to='images/'),
        ),
    ]
