# Generated by Django 3.2.3 on 2021-08-08 23:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customeruser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
