# Generated by Django 3.2.3 on 2021-08-12 00:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customeruser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_susbwu.JPG', max_length=255, verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='upload',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='uploads'),
        ),
    ]
