<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-08-04 19:34
=======
# Generated by Django 3.2.3 on 2021-08-05 11:51
>>>>>>> b526e302c3bc81d89de9d6584c2d43a7443ed2f0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
